---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base-dev
  labels:
    pipelines.weave.works/name: base
    pipelines.weave.works/stage: "0"
spec:
  interval: 1m0s
  path: ./base/dev
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: pipelines
    namespace: flux-system
